### ISSUE TITLE
No pull request can be found

### ISSUE THREAD

**Issue by diskostu** [shiraji/find-pull-request#31]
In our company, we have an installation of GitHub Enterprise  (I do not know the exact version, but I think it is a fairly recent one).
When I choose "Find pull request" on a line which is part of a pull request, I always get the info "pull request not found". This applies to closed pull requests and open ones as well.

"Open the commit page" works well.
I am glad to provide more info or a log file... if you tell me where to find it.

**Comment by shiraji** [comment]
Oops. I'm sorry @diskostu I didn't notice this issue somehow.

Can you provide the open source repository that reproduces this problem? Since this problem is highly related to the repository and development flow, it's quite hard to find what's going on from your comment.

Some questions I come up are 
* Does your company squash PR commits and customize the commit message?
* Does the commit merge to `master` branch?
* Do you set `origin` or `upstream` repository?
* Do you use multiple repository?

**Comment by diskostu** [comment]
I use IntelliJ with our GitHub Enterprise installation. I cannot switch to public GitHub that easy. The repository is not open source.
For your questions:

- no, the commit message is not customized.
- I tried pushing to different remote branches, not only master
- I do not really know what this question is about... we have a remote server called origin.
- no, we only have 1 remote repository

**Comment by shiraji** [comment]
Don't worry about Github Enterprise, because you already said that you can jump to the commit page. (meaning this plugin successfully find the Github Enterprise URL)

> no, the commit message is not customized.

That's good start.

> I tried pushing to different remote branches, not only master

So, the commit is in `master` branch, right?

> I do not really know what this question is about... we have a remote server called origin.

`origin` is default name of remote url. How do you pull master branch? `git pull origin master`? That's `origin` I'm talking about. If you fork the repository, people set `upstream` url for forked repository. Check [this stackoverflow](https://stackoverflow.com/questions/9257533/what-is-the-difference-between-origin-and-upstream-on-github) 

> no, we only have 1 remote repository

That's good, too.

**Comment by diskostu** [comment]
I did the following:

1. I created a new branch. So I do not want to push to master.
1. I did a change in the file system and pushed the change to the remote repository (origin, but a new feature branch).
1. I opened a pull request for this branch.

Then, I executed the first command you suggested. I took the commit hash from the demo change. The command returned nothing. I think this is already not correct.

Maybe I am doing something wrong. And maybe it is a good idea if you could give me the alpha version with verbose logging :-)

**Comment by shiraji** [comment]
Thanks. Can you merge the pull request? This plugin is for finding **merged** pull request. I don't come up with the use case of finding currently open pull request.

**Comment by diskostu** [comment]
Ah, I see. I did not know that this plugin finds **merged** pull requests. My mistake.
I tried it with some code from a merged pull request, it works perfectly fine.
